openapi: 3.0.0
info:
  title: "Accounting path segment used to group related resources"
  version: "1.0.0"
paths: 
  /{datapartition}/invoices:
    parameters:
      - $ref: "#/components/parameters/datapartition"
    get:
      responses:
        200: 
          description: ok
  /{datapartition}/generalLedger:
    parameters:
      - $ref: "#/components/parameters/datapartition"
    get:
      responses:
        200: 
          description: ok
  /{datapartition}/accounts:
    parameters:
      - $ref: "#/components/parameters/datapartition"
    get:
      responses:
        200: 
          description: ok
components:
  parameters:
    datapartition:
      name: datapartition
      in: path
      required: true
      schema:
        type: string
